[workspace]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "anpr"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
anpr = "mojo run src/anpr.mojo"
webcam = "mojo run src/webcam.mojo"

[dependencies]
mojo = ">=25.5.0,<26"
